### ISSUE TITLE
C++ LoC count doesn't consider .h or .hop files

### ISSUE THREAD

**Issue by Gonzalo-Mier** [PabloLec/StarryLines#63]
The LoC should count files .c, .cpp, .cxx, .h, .hpp, .hxx.

**To Reproduce**
Error observed at the webpage on table with C++ filter. https://github.com/progschj/ThreadPool have 22 lines with correspond to the example.cpp file, but the actual library file is not counted.

**Comment by PabloLec** [comment]
Hi @Gonzalo-Mier,

Good call, thanks for the issue, `.h`, `.hop` and `.c` were missing, I just added those.
